### ISSUE TITLE
Set up robot radio

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2016#2]
Set up the Open Mesh robot radio.  Establish communication with the roboRIO.

**Comment by Daniel-Heyde** [comment]
Radio is set up. Name is 1388, Password is Team1388.

**Comment by jtechau** [comment]
I recommend naming the radio 1388-2016.  We have numerous robots / 
radios, which often operate at the same time.  In the past, we've 
distinguished them using the above naming convention.

**Comment by Daniel-Heyde** [comment]
Radio name has been changed to 1388-2016.
